spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/fbfagostousa
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

server:
  port: 8081